# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c23519b81b8e6ffaebe7ea139cfa6e39a8e2e1dd0088d4b2068c981975c533cb974338f8536b3759bc11489a623e455accd2e4553dd1f7b7c3df3d8a1f9a8455

test:
  secret_key_base: c844baca4369d18b02f369136ffd58615903e5173ffd8655adbfac21a0768c06f76332df8068cc24409785d1b49e26c90b22d74ac1dfc36a9f7958c5acc6c968

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
